import os
import re
from decimal import Decimal, ROUND_UP
from dotenv import load_dotenv
from flask import Flask, request, jsonify, render_template, redirect, url_for, flash, session
from flask_login import LoginManager, login_user, logout_user, login_required, current_user
from authlib.integrations.flask_client import OAuth

# --- AI IMPORTS ---
# We only need Groq and LangChain core libraries now
from langchain_groq import ChatGroq
from langchain_community.tools import DuckDuckGoSearchRun
from langchain_core.tools import tool
from langchain_core.messages import HumanMessage, SystemMessage, ToolMessage, AIMessage, BaseMessage
from langgraph.graph import StateGraph, END
from langgraph.checkpoint.sqlite import SqliteSaver
from langgraph.checkpoint.postgres import PostgresSaver
from psycopg_pool import ConnectionPool
from typing import TypedDict, Annotated, List
import operator

# --- DATABASE MODELS ---
from models import db, User

# --- SETUP ---
load_dotenv()
app = Flask(__name__, template_folder='templates')

# --- CONFIG ---
app.config['SECRET_KEY'] = os.environ.get('FLASK_SECRET_KEY')
app.config['SQLALCHEMY_DATABASE_URI'] = os.environ.get('DATABASE_URL')
app.config['YOUR_DOMAIN'] = os.environ.get('YOUR_DOMAIN')
app.config['SESSION_COOKIE_SECURE'] = False
app.config['SESSION_COOKIE_HTTPONLY'] = True
app.config['SESSION_COOKIE_SAMESITE'] = 'Lax'

# Auth0
app.config['AUTH0_CLIENT_ID'] = os.environ.get('AUTH0_CLIENT_ID')
app.config['AUTH0_CLIENT_SECRET'] = os.environ.get('AUTH0_CLIENT_SECRET')
app.config['AUTH0_DOMAIN'] = os.environ.get('AUTH0_DOMAIN')

db.init_app(app)

# --- LOGIN MANAGER ---
login_manager = LoginManager()
login_manager.login_view = 'login'
login_manager.init_app(app)

@login_manager.user_loader
def load_user(user_id):
    return db.session.get(User, int(user_id))

# --- OAUTH ---
oauth = OAuth(app)
auth0 = oauth.register(
    'auth0',
    client_id=app.config['AUTH0_CLIENT_ID'],
    client_secret=app.config['AUTH0_CLIENT_SECRET'],
    api_base_url=f"https://{app.config['AUTH0_DOMAIN']}",
    access_token_url=f"https://{app.config['AUTH0_DOMAIN']}/oauth/token",
    authorize_url=f"https://{app.config['AUTH0_DOMAIN']}/authorize",
    client_kwargs={'scope': 'openid profile email'},
    server_metadata_url=f"https://{app.config['AUTH0_DOMAIN']}/.well-known/openid-configuration"
)

# ==============================================================================
# 1. INITIALIZE THE "ALL-IN-ONE" EMPLOYEE (GROQ)
# ==============================================================================

try:
    # We use one powerful, free model for EVERYTHING.
    groq_llm = ChatGroq(
        model_name='llama-3.3-70b-versatile', 
        api_key=os.environ.get('GROQ_API_KEY')
    )
    print("✅ Groq AI Client Initialized Successfully")

except Exception as e:
    print(f"CRITICAL: AI Client failed to load. {e}")

# ==============================================================================
# 2. DEFINE THE TOOLS
# ==============================================================================

@tool
def ui_builder_tool(prompt: str) -> str:
    """
    Use this tool to generate HTML, CSS, React, or Frontend code.
    """
    messages = [
        SystemMessage(content="You are an expert Frontend Developer. Generate clean, modern HTML/Tailwind code."),
        HumanMessage(content=prompt)
    ]
    # Use Groq for UI generation
    response = groq_llm.invoke(messages)
    return f"[UI Generated by Groq] \n\n {response.content}"

@tool
def backend_builder_tool(prompt: str) -> str:
    """
    Use this tool to generate Python, Flask, SQL, or complex Backend logic.
    """
    messages = [
        SystemMessage(content="You are a Senior Backend Engineer. Write secure, production-ready Python code."),
        HumanMessage(content=prompt)
    ]
    # Use Groq for Backend generation
    response = groq_llm.invoke(messages)
    return f"[Backend Generated by Groq] \n\n {response.content}"

@tool
def web_search_tool(query: str) -> str:
    """
    Use this tool to find real-time information, news, weather, or current events.
    """
    search = DuckDuckGoSearchRun()
    return search.invoke(query)

# ==============================================================================
# 3. BUILD THE AGENT GRAPH
# ==============================================================================

# Groq acts as the "Brain" and has access to all tools
tools = [ui_builder_tool, backend_builder_tool, web_search_tool]
agent_brain = groq_llm.bind_tools(tools)

class AgentState(TypedDict):
    messages: Annotated[List[BaseMessage], operator.add]

# Node 1: The Brain
def brain_node(state):
    return {"messages": [agent_brain.invoke(state["messages"])]}

# Node 2: The Tools
def tool_node(state):
    last_message = state["messages"][-1]
    tool_calls = last_message.tool_calls
    results = []
    
    for t in tool_calls:
        # Select tool
        selected_tool = {
            "ui_builder_tool": ui_builder_tool,
            "backend_builder_tool": backend_builder_tool,
            "web_search_tool": web_search_tool
        }.get(t["name"])
        
        if selected_tool:
            # Run tool
            output = selected_tool.invoke(t["args"])
            results.append(ToolMessage(tool_call_id=t['id'], name=t['name'], content=str(output)))
            
    return {"messages": results}

def should_continue(state):
    last_message = state["messages"][-1]
    if last_message.tool_calls:
        return "tools"
    return END

workflow = StateGraph(AgentState)
workflow.add_node("brain", brain_node)
workflow.add_node("tools", tool_node)
workflow.set_entry_point("brain")
workflow.add_conditional_edges("brain", should_continue, {"tools": "tools", END: END})
workflow.add_edge("tools", "brain")

# --- DATABASE CONNECTION & CHECKPOINTING ---
db_url = os.environ.get("DATABASE_URL")
memory_checkpointer = None

if db_url and db_url.startswith("postgresql"):
    # PRODUCTION
    print("--- Connecting to PostgreSQL (Production) ---")
    pool = ConnectionPool(conninfo=db_url, max_size=20, kwargs={"autocommit": True})
    memory_checkpointer = PostgresSaver(pool)
    
    with app.app_context():
        db.create_all()
        memory_checkpointer.setup()
else:
    # LOCAL
    print("--- Using SQLite (Local Development) ---")
    memory_checkpointer = SqliteSaver.from_conn_string("checkpoints.sqlite")
    with app.app_context():
        db.create_all()

agent_app = workflow.compile(checkpointer=memory_checkpointer)

# ==============================================================================
# 4. ROUTING & API
# ==============================================================================

def simple_chat(prompt):
    """Direct chat with Groq"""
    return groq_llm.invoke([HumanMessage(content=prompt)]).content

@app.route("/api/ask", methods=["POST"])
@login_required
def handle_ask():
    user_prompt = request.json.get("prompt")
    user_id = current_user.auth0_id
    
    # --- STEP 1: ROUTING ---
    router_system = """
    Classify this prompt.
    1. 'simple': Greetings, jokes, definitions, general knowledge.
    2. 'complex': Requests for code, weather, news, analysis, or multi-step tasks.
    Return ONLY 'simple' or 'complex'.
    """
    try:
        classification = groq_llm.invoke([
            SystemMessage(content=router_system), 
            HumanMessage(content=user_prompt)
        ]).content.strip().lower()
    except:
        classification = 'complex' 

    final_answer = ""
    
    # Groq is free, so cost is 0.00
    cost_estimate = 0.0

    # --- STEP 2: EXECUTION ---
    if "simple" in classification:
        final_answer = simple_chat(user_prompt)
    else:
        # Complex path: Agent with Tools (still Groq-powered)
        config = {"configurable": {"thread_id": user_id}}
        result = agent_app.invoke(
            {"messages": [HumanMessage(content=user_prompt)]}, 
            config=config
        )
        final_answer = result["messages"][-1].content

    # --- STEP 3: BILLING (Free for now) ---
    # We deduct 0 credits because you aren't paying for Groq
    current_user.credits -= Decimal(cost_estimate)
    db.session.commit()

    return jsonify({
        "answer": final_answer,
        "cost": cost_estimate,
        "remaining": float(current_user.credits)
    })

# --- STANDARD ROUTES ---
@app.route('/')
def index():
    if current_user.is_authenticated: return redirect(url_for('chat_interface'))
    return render_template('landing.html')

@app.route('/app')
@login_required
def chat_interface():
    return render_template('ai_assistant.html', user_credits=current_user.get_credit_balance())

@app.route('/login')
def login(): return oauth.auth0.authorize_redirect(redirect_uri=url_for('callback', _external=True))

@app.route('/signup')
def signup(): return oauth.auth0.authorize_redirect(redirect_uri=url_for('callback', _external=True), screen_hint='signup')

@app.route('/callback')
def callback():
    try:
        token = oauth.auth0.authorize_access_token()
        user_info = auth0.get('userinfo').json()
        auth0_id = user_info.get('sub')
        email = user_info.get('email')
        
        user = User.query.filter_by(auth0_id=auth0_id).first()
        if not user:
            user = User(auth0_id=auth0_id, email=email, credits=Decimal('50.0'))
            db.session.add(user)
            db.session.commit()
        
        login_user(user, remember=True)
        return redirect(url_for('chat_interface'))
    except Exception as e:
        print(f"Error during callback: {e}")
        return redirect(url_for('index'))

@app.route('/logout')
def logout():
    session.clear()
    logout_user()
    return redirect(f"https://{app.config['AUTH0_DOMAIN']}/v2/logout?client_id={app.config['AUTH0_CLIENT_ID']}&returnTo={url_for('index', _external=True)}")

@app.route('/pricing')
@login_required
def pricing_page():
    return render_template('pricing.html')

if __name__ == "__main__":
    # Local run
    with app.app_context(): db.create_all()
    app.run(host='0.0.0.0', port=5000, debug=True)